version: "3"
services: 
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - REACT_APP_NAME=kim
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
